/**
 * IMAGE OPTIMIZATION GUIDE
 * 
 * Use this component when adding hero or any above-fold images to ensure
 * compliance with Web Vitals targets (LCP <2.5s, CLS <0.1)
 */

'use client'

import Image from 'next/image'
import { useMemo } from 'react'

interface ResponsiveHeroImageProps {
  src: string
  alt: string
  priority?: boolean
  // Placeholder blur data URL (generate via: https://www.plaiceholder.co/)
  blurDataURL?: string
  quality?: number
  width?: number
  height?: number
}

/**
 * ResponsiveHeroImage
 * 
 * Optimized image component for hero sections with:
 * - Automatic WebP/AVIF format selection
 * - Responsive srcset for all breakpoints
 * - Blur placeholder to prevent CLS
 * - Priority loading for above-fold content
 * 
 * @example
 * <ResponsiveHeroImage
 *   src="/images/hero-therapist.jpg"
 *   alt="Rainuka, Licensed Therapist"
 *   priority={true}
 *   width={1200}
 *   height={800}
 *   blurDataURL="data:image/jpeg;base64,/9j/4AAQSkZJRgABA..."
 * />
 */
export function ResponsiveHeroImage({
  src,
  alt,
  priority = true,
  blurDataURL,
  quality = 85,
  width = 1200,
  height = 800,
}: ResponsiveHeroImageProps) {
  // Verify image dimensions are set (required for Next.js Image)
  if (!width || !height) {
    console.warn('[Image] Missing width/height for:', alt)
  }

  const aspectRatio = width / height

  return (
    <div
      style={{
        position: 'relative',
        aspectRatio,
        overflow: 'hidden',
        borderRadius: '1.75rem',
      }}
    >
      <Image
        src={src}
        alt={alt}
        width={width}
        height={height}
        priority={priority}
        quality={quality}
        placeholder={blurDataURL ? 'blur' : 'empty'}
        blurDataURL={blurDataURL}
        sizes={
          '(max-width: 640px) 100vw, (max-width: 1024px) 80vw, 1200px'
        }
        style={{
          objectFit: 'cover',
          width: '100%',
          height: '100%',
        }}
      />
    </div>
  )
}

/**
 * IMAGE OPTIMIZATION CHECKLIST
 * 
 * Before deploying a new image:
 * 
 * ✓ File Size
 *   - Hero images: <100KB (200KB max)
 *   - Thumbnails: <50KB
 *   - Generate blur placeholder (https://www.plaiceholder.co/)
 * 
 * ✓ Dimensions
 *   - Hero: 1200x800px (4:5 ratio on desktop, 4:3.4 on mobile)
 *   - Always set explicit width/height props
 *   - Use `sizes` prop to hint responsive breakpoints
 * 
 * ✓ Format Selection
 *   - JPEG for photography (use quality: 80-85)
 *   - PNG for graphics/screenshots
 *   - WebP auto-generated by next/image
 *   - AVIF auto-generated by next/image
 * 
 * ✓ LCP Impact
 *   - Hero image: priority={true}
 *   - Below-fold images: priority={false} (default)
 *   - Monitor LCP via console: [Perf] LCP: ...ms
 * 
 * ✓ CLS Prevention
 *   - Always use placeholder="blur" with blurDataURL
 *   - Set explicit aspect ratio via width/height
 *   - Never omit width/height (causes layout shift)
 * 
 * ✓ Responsive Breakpoints
 *   - Mobile: 640px
 *   - Tablet: 1024px
 *   - Desktop: 1200px+
 * 
 * ✓ Testing
 *   1. Chrome DevTools → Lighthouse → Run Audit
 *   2. Verify LCP < 2.5s
 *   3. Verify CLS < 0.1
 *   4. Check console for: [Perf] LCP Status: ✓ GOOD
 *   5. Test on real device with slow 4G throttling
 */

/**
 * PERFORMANCE TARGETS
 * 
 * Metric          | Target  | Good  | Needs Improvement
 * LCP             | 2.5s    | <1.2s | >2.5s
 * FCP             | 1.8s    | <1.0s | >1.8s
 * CLS             | 0.1     | <0.01 | >0.25
 * INP             | 200ms   | <100ms| >500ms
 * TTFB            | 600ms   | <200ms| >600ms
 */

/**
 * HOW TO GENERATE BLUR PLACEHOLDER
 * 
 * 1. Visit https://www.plaiceholder.co/
 * 2. Upload your optimized image
 * 3. Copy the blurDataURL value
 * 4. Paste into the component:
 * 
 *    <ResponsiveHeroImage
 *      src="/images/hero.jpg"
 *      alt="..."
 *      blurDataURL="data:image/jpeg;base64,/9j/4AAQ..."
 *    />
 */

/**
 * CLI TOOLS FOR IMAGE OPTIMIZATION
 * 
 * Resize and optimize images:
 * $ npx sharp-cli -i input.jpg -o output.jpg --resize 1200 800 --quality 85
 * 
 * Convert to WebP:
 * $ npx sharp-cli -i input.jpg -o input.webp --format webp --quality 85
 * 
 * Generate blur placeholder:
 * $ npx plaiceholder /path/to/image.jpg
 */
